name: Deploy docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install system dependencies
        run: sudo apt-get install gdal-bin spatialite-bin libsqlite3-mod-spatialite

      - name: Install Hatch
        run: pip install hatch

      - name: Build docs
        run: cd kronofoto && hatch run docs:build

      - name: Upload docs artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: kronofoto/site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
